<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFrameworks>net10.0-windows;net10.0</TargetFrameworks>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>

        <!-- Ignore warning for duplicate WebView2 -->
        <NoWarn>MSB3277</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit.Analyzers"/>
        <PackageReference Include="NUnit3TestAdapter"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Dmnk.Blazor.InteractiveTests.FluentUIHelpers\Dmnk.Blazor.InteractiveTests.FluentUIHelpers.csproj" />
      <ProjectReference Include="..\Dmnk.Blazor.InteractiveTests.TestComponents\Dmnk.Blazor.InteractiveTests.TestComponents.csproj" />
      <ProjectReference Include="..\Dmnk.Blazor.InteractiveTests\Dmnk.Blazor.InteractiveTests.csproj" />
    </ItemGroup>

</Project>
