//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dmnk.LocalizedDataAnnotations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18nLocalizedDataAnnotations_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18nLocalizedDataAnnotations_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dmnk.LocalizedDataAnnotations.Properties.I18nLocalizedDataAnnotations.fr", typeof(I18nLocalizedDataAnnotations_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} ne correspond à aucune des valeurs autorisées..
        /// </summary>
        internal static string AllowedValuesAttribute_Invalid {
            get {
                return ResourceManager.GetString("AllowedValuesAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;argument &apos;{0}&apos; ne peut pas être Null, vide, ou contenir uniquement un espace blanc..
        /// </summary>
        internal static string ArgumentIsNullOrWhitespace {
            get {
                return ResourceManager.GetString("ArgumentIsNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type de métadonnées associé pour le type &apos;{0}&apos; contient les propriétés ou champs inconnus suivants : {1}. Vérifiez que les noms de ces membres correspondent aux noms des propriétés du type principal..
        /// </summary>
        internal static string AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties {
            get {
                return ResourceManager.GetString("AssociatedMetadataTypeTypeDescriptor_MetadataTypeContainsUnknownProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type &apos;{0}&apos; doit être public..
        /// </summary>
        internal static string AttributeStore_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("AttributeStore_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type &apos;{0}&apos; ne contient aucune méthode publique appelée &apos;{1}&apos;..
        /// </summary>
        internal static string AttributeStore_Unknown_Method {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type &apos;{0}&apos; ne contient aucune propriété publique appelée &apos;{1}&apos;..
        /// </summary>
        internal static string AttributeStore_Unknown_Property {
            get {
                return ResourceManager.GetString("AttributeStore_Unknown_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} n’est pas un encodage Base64 valide..
        /// </summary>
        internal static string Base64StringAttribute_Invalid {
            get {
                return ResourceManager.GetString("Base64StringAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur ne peut pas être null ou vide..
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propriété {0}.{1} est introuvable..
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; et &apos;{1}&apos; ne correspondent pas..
        /// </summary>
        internal static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de trouver une propriété nommée {0}..
        /// </summary>
        internal static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} n&apos;est pas un numéro de carte de crédit valide..
        /// </summary>
        internal static string CreditCardAttribute_Invalid {
            get {
                return ResourceManager.GetString("CreditCardAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La méthode CustomValidationAttribute &apos;{0}&apos; dans le type &apos;{1}&apos; doit retourner System.ComponentModel.DataAnnotations.ValidationResult. Utilisez System.ComponentModel.DataAnnotations.ValidationResult.Success pour représenter la réussite..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Must_Return_ValidationResult {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Must_Return_ValidationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La méthode CustomValidationAttribute &apos;{0}&apos; n&apos;existe pas dans le type &apos;{1}&apos; ou n&apos;est pas publique ni statique..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Not_Found {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomValidationAttribute.Method n&apos;a pas été spécifié..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La méthode CustomValidationAttribute &apos;{0}&apos; dans le type &apos;{1}&apos; doit correspondre à la signature attendue : public static ValidationResult {0}(valeur d&apos;objet, contexte ValidationContext). La valeur peut être fortement typée. Le paramètre ValidationContext est optionnel..
        /// </summary>
        internal static string CustomValidationAttribute_Method_Signature {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Method_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de convertir la valeur de type &apos;{0}&apos; en &apos;{1}&apos; comme prévu par la méthode {2}.{3}..
        /// </summary>
        internal static string CustomValidationAttribute_Type_Conversion_Failed {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Conversion_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type de validation personnalisé &apos;{0}&apos; doit être public..
        /// </summary>
        internal static string CustomValidationAttribute_Type_Must_Be_Public {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_Type_Must_Be_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} n&apos;est pas valide..
        /// </summary>
        internal static string CustomValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomValidationAttribute.ValidatorType n&apos;a pas été spécifié..
        /// </summary>
        internal static string CustomValidationAttribute_ValidatorType_Required {
            get {
                return ResourceManager.GetString("CustomValidationAttribute_ValidatorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La chaîne DataType personnalisée ne peut pas être null ou vide..
        /// </summary>
        internal static string DataTypeAttribute_EmptyDataTypeString {
            get {
                return ResourceManager.GetString("DataTypeAttribute_EmptyDataTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} correspond à l’une des valeurs interdites..
        /// </summary>
        internal static string DeniedValuesAttribute_Invalid {
            get {
                return ResourceManager.GetString("DeniedValuesAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propriété {0} n&apos;a pas été définie. Utilisez la méthode {1} pour obtenir la valeur..
        /// </summary>
        internal static string DisplayAttribute_PropertyNotSet {
            get {
                return ResourceManager.GetString("DisplayAttribute_PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} n&apos;est pas une adresse électronique valide..
        /// </summary>
        internal static string EmailAddressAttribute_Invalid {
            get {
                return ResourceManager.GetString("EmailAddressAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type fourni pour EnumDataTypeAttribute ne peut pas avoir la valeur null..
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type &apos;{0}&apos; doit représenter un type d&apos;énumération..
        /// </summary>
        internal static string EnumDataTypeAttribute_TypeNeedsToBeAnEnum {
            get {
                return ResourceManager.GetString("EnumDataTypeAttribute_TypeNeedsToBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} accepte uniquement les fichiers portant les extensions suivantes : {1}.
        /// </summary>
        internal static string FileExtensionsAttribute_Invalid {
            get {
                return ResourceManager.GetString("FileExtensionsAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthAttribute must have a MaximumLength value that is greater than or equal to MinimumLength..
        /// </summary>
        internal static string LengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("LengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthAttribute must have a MinimumLength value that is zero or greater..
        /// </summary>
        internal static string LengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("LengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthAttribute must have a MinimumLength value that is zero or greater..
        /// </summary>
        internal static string LengthAttribute_InvalidValueType {
            get {
                return ResourceManager.GetString("LengthAttribute_InvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être une chaîne ou un type de collection avec une longueur minimale de « {1} » et une longueur maximale de « {2} »..
        /// </summary>
        internal static string LengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("LengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de récupérer la propriété &apos;{0}&apos; en raison de l&apos;échec de la localisation. Le type &apos;{1}&apos; n&apos;est pas public ou ne contient pas une propriété de chaîne statique publique avec le nom &apos;{2}&apos;..
        /// </summary>
        internal static string LocalizableString_LocalizationFailed {
            get {
                return ResourceManager.GetString("LocalizableString_LocalizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxLengthAttribute doit avoir une valeur Length supérieure à zéro. Utilisez MaxLength() sans paramètres pour indiquer que la chaîne ou le tableau peut avoir la longueur maximum autorisée..
        /// </summary>
        internal static string MaxLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être un type chaîne ou tableau d&apos;une longueur maximum de &apos;{1}&apos;..
        /// </summary>
        internal static string MaxLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MaxLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetadataClassType ne peut pas avoir la valeur null..
        /// </summary>
        internal static string MetadataTypeAttribute_TypeCannotBeNull {
            get {
                return ResourceManager.GetString("MetadataTypeAttribute_TypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLengthAttribute doit avoir une valeur Length supérieure ou égale à zéro..
        /// </summary>
        internal static string MinLengthAttribute_InvalidMinLength {
            get {
                return ResourceManager.GetString("MinLengthAttribute_InvalidMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être un type chaîne ou tableau d&apos;une longueur minimum de &apos;{1}&apos;..
        /// </summary>
        internal static string MinLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("MinLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} n&apos;est pas un numéro de téléphone valide..
        /// </summary>
        internal static string PhoneAttribute_Invalid {
            get {
                return ResourceManager.GetString("PhoneAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type {0} doit implémenter {1}..
        /// </summary>
        internal static string RangeAttribute_ArbitraryTypeNotIComparable {
            get {
                return ResourceManager.GetString("RangeAttribute_ArbitraryTypeNotIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use exclusive bounds when the maximum value is equal to the minimum value..
        /// </summary>
        internal static string RangeAttribute_CannotUseExclusiveBoundsWhenTheyAreEqual {
            get {
                return ResourceManager.GetString("RangeAttribute_CannotUseExclusiveBoundsWhenTheyAreEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur maximale &apos;{0}&apos; doit être supérieure ou égale à la valeur minimale &apos;{1}&apos;..
        /// </summary>
        internal static string RangeAttribute_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("RangeAttribute_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les valeurs minimale et maximale doivent être définies..
        /// </summary>
        internal static string RangeAttribute_Must_Set_Min_And_Max {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Min_And_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type OperandType doit être défini lorsque des chaînes sont utilisées pour les valeurs minimale et maximale..
        /// </summary>
        internal static string RangeAttribute_Must_Set_Operand_Type {
            get {
                return ResourceManager.GetString("RangeAttribute_Must_Set_Operand_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être compris entre {1} et {2}..
        /// </summary>
        internal static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être compris strictement entre {1} et {2}..
        /// </summary>
        internal static string RangeAttribute_ValidationError_MaxExclusive {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError_MaxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être compris entre {1} exclus et {2}..
        /// </summary>
        internal static string RangeAttribute_ValidationError_MinExclusive {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError_MinExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être compris strictement entre {1} et {2}..
        /// </summary>
        internal static string RangeAttribute_ValidationError_MinExclusive_MaxExclusive {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError_MinExclusive_MaxExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit correspondre à l&apos;expression régulière &apos;{1}&apos;..
        /// </summary>
        internal static string RegexAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RegexAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le modèle doit avoir pour valeur une expression régulière valide..
        /// </summary>
        internal static string RegularExpressionAttribute_Empty_Pattern {
            get {
                return ResourceManager.GetString("RegularExpressionAttribute_Empty_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} est requis..
        /// </summary>
        internal static string RequiredAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RequiredAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur maximale doit être un entier non négatif..
        /// </summary>
        internal static string StringLengthAttribute_InvalidMaxLength {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être une chaîne dont la longueur maximale est de {1}..
        /// </summary>
        internal static string StringLengthAttribute_ValidationError {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} doit être une chaîne d&apos;une longueur minimale de {2} et d&apos;une longueur maximale de {1}..
        /// </summary>
        internal static string StringLengthAttribute_ValidationErrorIncludingMinimum {
            get {
                return ResourceManager.GetString("StringLengthAttribute_ValidationErrorIncludingMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le paramètre de clé à la position {0} avec la valeur &apos;{1}&apos; n&apos;est pas une chaîne. Chaque paramètre de contrôle de clé doit être une chaîne..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNotAString {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNotAString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le paramètre de clé à la position {0} est null. Chaque paramètre de contrôle de clé doit être une chaîne..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyIsNull {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le paramètre de clé à la position {0} avec la valeur &apos;{1}&apos; apparaît plusieurs fois..
        /// </summary>
        internal static string UIHintImplementation_ControlParameterKeyOccursMoreThanOnce {
            get {
                return ResourceManager.GetString("UIHintImplementation_ControlParameterKeyOccursMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nombre de paramètres de contrôle doit être pair..
        /// </summary>
        internal static string UIHintImplementation_NeedEvenNumberOfControlParameters {
            get {
                return ResourceManager.GetString("UIHintImplementation_NeedEvenNumberOfControlParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} n&apos;est pas une URL HTTP, HTTPS ou FTP complète valide..
        /// </summary>
        internal static string UrlAttribute_Invalid {
            get {
                return ResourceManager.GetString("UrlAttribute_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessageString ou ErrorMessageResourceName doit être défini, mais pas les deux..
        /// </summary>
        internal static string ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource {
            get {
                return ResourceManager.GetString("ValidationAttribute_Cannot_Set_ErrorMessage_And_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValid(object value) n&apos;a pas été implémenté par cette classe. Le point d&apos;entrée par défaut est GetValidationResult() et les classes doivent remplacer IsValid(object value, ValidationContext context)..
        /// </summary>
        internal static string ValidationAttribute_IsValid_NotImplemented {
            get {
                return ResourceManager.GetString("ValidationAttribute_IsValid_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMessageResourceType et ErrorMessageResourceName doivent être définis sur cet attribut..
        /// </summary>
        internal static string ValidationAttribute_NeedBothResourceTypeAndResourceName {
            get {
                return ResourceManager.GetString("ValidationAttribute_NeedBothResourceTypeAndResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propriété &apos;{0}&apos; du type de ressource &apos;{1}&apos; n&apos;est pas de type chaîne..
        /// </summary>
        internal static string ValidationAttribute_ResourcePropertyNotStringType {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourcePropertyNotStringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le type de ressource &apos;{0}&apos; n&apos;a pas de propriété statique accessible nommée &apos;{1}&apos;..
        /// </summary>
        internal static string ValidationAttribute_ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ValidationAttribute_ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0} n&apos;est pas valide..
        /// </summary>
        internal static string ValidationAttribute_ValidationError {
            get {
                return ResourceManager.GetString("ValidationAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ValidationContext pour le type &apos;{0}&apos;, nom de membre &apos;{1}&apos;, doit fournir MethodInfo..
        /// </summary>
        internal static string ValidationContext_Must_Be_Method {
            get {
                return ResourceManager.GetString("ValidationContext_Must_Be_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un service de type &apos;{0}&apos; existe déjà dans le conteneur..
        /// </summary>
        internal static string ValidationContextServiceContainer_ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ValidationContextServiceContainer_ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;instance indiquée doit correspondre à ObjectInstance dans le ValidationContext fourni..
        /// </summary>
        internal static string Validator_InstanceMustMatchValidationContextInstance {
            get {
                return ResourceManager.GetString("Validator_InstanceMustMatchValidationContextInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La valeur de la propriété &apos;{0}&apos; doit être de type &apos;{1}&apos;..
        /// </summary>
        internal static string Validator_Property_Value_Wrong_Type {
            get {
                return ResourceManager.GetString("Validator_Property_Value_Wrong_Type", resourceCulture);
            }
        }
    }
}
