name: Publish to NuGet (.org)

on:
  release:
    types:
      - published
  # Allow manual triggering
  workflow_dispatch:

jobs:
  pack-and-publish:
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 10.0.x

      - name: dotnet pack
        run: dotnet cake.cs --target=pack --configuration=Release

      - name: NuGet login (OIDC → temp API key) # Get a short-lived NuGet API key
        uses: NuGet/login@v1
        id: login
        with:
          user: dominiksta
    
      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate